### ISSUE TITLE
[Bug] Test RuntimeError: Expected all tensors to be on the same device, but found at least two devices

### ISSUE THREAD

**Issue by kevinzhangcode** [Chiang97912/dssm#1]
## 问题描述
使用Test样例：
```
for query in queries_cut:
    for doc in documents_cut:    
        text_left = query
        text_right = doc
        model = DSSM('./dssm-model', device='cuda:1')
        vectors = model.encode([text_left, text_right])
```

`错误信息`如下：

```
Traceback (most recent call last):
  File "/xxxxxx/workspace/xxxxxx/eval_cuda.py", line 20, in <module>
    vectors = model.encode([text_left, text_right])
  File "/xxxxxx/miniconda3/envs/xxxxxx/lib/python3.9/site-packages/dssm/model.py", line 257, in encode
    vectors = self.mlp_left(vectors).tolist()
  File "/xxxxxx/miniconda3/envs/xxxxxx/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/xxxxxx/miniconda3/envs/xxxxxx/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/xxxxxx/envs/xxxxxx/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/xxxxxx/miniconda3/envs/xxxxxx/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/xxxxxx/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/xxxxxx/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 103, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cpu! (when checking argument for argument mat1 in method wrapper_addmm)
```

**Comment by Chiang97912** [comment]
测试的时候用CPU试试，不行的话改一下第256行的代码：
`vectors = torch.FloatTensor(vectors).to(self.device)`

**Comment by kevinzhangcode** [comment]
谢谢🙏，GPU可以指定了，就是这一行的问题，建议更新下文件 @Chiang97912

**Comment by Chiang97912** [comment]
代码更新了，可以从pypi更新一下版本。
